name = "Nightly"
uuid = "00b13223-84b7-4867-b81f-24991e8c39ea"
version = "0.1.0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]

[extras]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[targets]
test = ["InteractiveUtils"]
